### ISSUE TITLE
Subtitle Upload within Media File doesn´t work

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#322] opened 2016-04-14 11:49 UTC
Hi,

I tried to upload a subtitles file (.vtt) within a video media element (Add Track => Choose from Library) and clicked on Upload. I selected the .vtt file but the upload doesn´t start. Chrome console error: 
`load-scripts.php?c=0&load[]=thickbox,jquery-ui-mouse,jquery-ui-resizable,jquery-ui-draggable,jquery…:504 Uncaught TypeError: Cannot read property 'text' of undefined
`
The default file upload with vtt works.

**Comment by kylegilman** [comment] 2016-04-14 14:21
Yeah, this is an old bug. I've never managed to get a handle on the inner workings of this window.

I'm closing this issue because it's a duplicate of #209, but feel free to add any ideas to that issue.

**Closed by kylegilman** 2016-04-14 14:21 UTC
Labels: type:bug
