### ISSUE TITLE
mpg, flv videos are not automatically encoded on upload

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#297] opened 2016-03-02 11:55 UTC
Hi,

I´ve uploaded mpg and flv video types and automatic encoding on upload is enabled, but these types aren´t automatically encoded. I used the default uploading procedure within the backend (creating posts etc.).

**Comment by kylegilman** [comment] 2016-03-02 14:09
I can't reproduce this bug. Once the mpg or flv file is uploaded, do you see the option to make thumbnails and encode manually? If not, then you need to make sure your MIME types for mpg and flv are set.

**Comment by benhartwich** [comment] 2016-03-08 07:46
Yes, I see these options. I´ve uploaded other video files before, but the mpg and flv videos are not added to the queue. Also a strange thumbnail is generated at mpg videos. 

Another question: The url to the video is generated by xy.mpg, but if I encode these video to mp4 (replace original) I got a mp4 url. Is this automatically recognized by the player, when the shortcode is placed with the .mpg url?

**Comment by benhartwich** [comment] 2016-03-08 12:00
The url is rewritten from .mpg to .mp4, but I get a 404 error (wordpress file url), example https://univideo.uni-passau.de/wp-content/uploads/2016/03/e137981c03d89bb904dfdccabcd6186b-1324307693.mp4.
The wordpress attachment url works: https://univideo.uni-passau.de/2011/12/kuwi-der-film-zum-ausgezeichneten-studiengang/e137981c03d89bb904dfdccabcd6186b_1324307693/

**Comment by kylegilman** [comment] 2016-03-08 12:44
I get a 403 forbidden error for that attachment URL.

**Comment by benhartwich** [comment] 2016-03-08 12:54
Sorry, now it should work.

**Comment by kylegilman** [comment] 2016-03-09 13:12
This is the danger of using software under development. If you're using a version of the plugin newer than 9 days, replacing videos has a bug that deletes the video file as soon as it starts encoding but doesn't tell any of the other processes, so everything keeps going like normal but there's no actual video there. #293 is tracking the problem. The attachment URL works because it's loading the 360p and custom resolution files.

**Comment by benhartwich** [comment] 2016-03-10 07:56
OK, this issue is already open? Or is there any patch I can do to get the already uploaded files working again?

**Comment by kylegilman** [comment] 2016-03-10 14:27
I don't understand. Did something happen to videos that you had already encoded two weeks ago? As far as I know this only affects currently encoding fullres replacements. If you're having another problem, please be as specific as possible.

I'll come up with a fix as soon as I can, but I'm back at work editing TV shows full time so I won't be able to work on this for free all day anymore. In the meantime, you could delete these lines https://github.com/kylegilman/video-embed-thumbnail-generator/blob/master/video-embed-thumbnail-generator.php#L3214-L3217

**Comment by kylegilman** [comment] 2016-04-07 13:25
Closing this because I think it was fixed.

**Closed by kylegilman** 2016-04-07 13:25 UTC
Labels: type:bug, type:support
